POST http://localhost:3003/partner
Content-Type: application/json

{
    "firstname": "Carlos Henrique",
    "lastname": "Rodrigues",
    "participation": 90
}


###
DELETE http://localhost:3003/partner/ae4ddac4-3e1b-4a7a-9032-88cd42afdcf0


###
GET  http://localhost:3003/partners
